<div align="center">

<img src="images/logo.jpg"  alt="输入图片"> 

[![License: CC BY 4.0](https://img.shields.io/badge/License-CC_BY_4.0-lightgrey.svg)](LICENSE)
[![Chinese](https://img.shields.io/badge/Chinese-Click_to_View-orange)](README.md)
[![English](https://img.shields.io/badge/English-Click_to_View-yellow)](README_en.md)
[![Japanese](https://img.shields.io/badge/日本語-クリックして表示-green)](README_ja.md)
[![Korean](https://img.shields.io/badge/한국어-눌러서_보기-blue)](README_kr.md)
[![Spanish](https://img.shields.io/badge/Español-Ver_Traducción-blueviolet)](README_es.md)
[![Turkish](https://img.shields.io/badge/Türkçe-Görüntülemek_için_Tıklayın-red)](README_tr.md)

</div>

> [!NOTE]
> We present Nano-consistent-150k — the first dataset constructed using Nano-Banana that exceeds 150k high-quality samples, uniquely designed to preserve consistent human identity across diverse and complex editing scenarios. A key feature is its remarkable identity consistency: for a single portrait, more than 35 distinct editing outputs are provided across diverse tasks and instructions. By anchoring on consistent human identities, the dataset enables the construction of interleaved data that seamlessly link multiple editing tasks, instructions, and modalities around the same individual.
<a href='https://picotrex.github.io/Awesome-Nano-Banana-images/'><img src='https://img.shields.io/badge/🌐 Website-Blog-orange' height="25"></a>
<a href='https://huggingface.co/datasets/Yejy53/Nano-consistent-150k'><img src='https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Dataset-yellow' height="25"></a>

## 🍌 Introduction

Welcome to the Nano-banana curated image gallery! 🤗 

**We have collected stunning images and prompts generated by Nano-banana in various task scenarios**, comprehensively showcasing Google's unlimited possibilities in image generation and editing. We hope this helps you better understand Nano-banana. Let's unlock Nano-banana's multi-image fusion and creative editing power together! ✨

These cases mainly come from Twitter/X 🐦, Xiaohongshu 📕 and other self-media platforms.

If you like it, please ⭐ Star to bookmark it!

## 📰 News

- **Nov-26-2025:** 6️⃣ Sixth repository update
- **Sep-24-2025:** 5️⃣ Fifth repository update
- **Sep-18-2025:** We released the **Nano-consistent-150k** dataset.
- **Sep-16-2025:** 4️⃣ Fourth repository update
- **Sep-9-2025:** 3️⃣ Third repository update
- **Sep-3-2025:** 2️⃣ Second repository update
- **Aug-28-2025:** 🎉 1️⃣ ${\color{red} First\ Awesome-Nano-Banana-images \ update!}$

## 📑 Menu

- [🍌 Introduction](#-introduction)
- [📰 News](#-news)
- [📑 Menu](#-menu)
- [🍌 Nano Banana Pro Examples](#-nano-banana-pro-examples)
  - [Example 1: Ukiyoe Flash Card (by @MANISH1027512)](#example-1-ukiyoe-flash-card-by-manish1027512)
  - [Example 2: Generate Image from Coordinates (by @TechieBySA)](#example-2-generate-image-from-coordinates-by-techiebysa)
  - [Example 3: Character Cloning (by @tapehead\_Lab)](#example-3-character-cloning-by-tapehead_lab)
  - [Example 4: Generate Flowchart from Document (by @anderssandberg)](#example-4-generate-flowchart-from-document-by-anderssandberg)
  - [Example 5: Create PPT from Article (by @op7418)](#example-5-create-ppt-from-article-by-op7418)
  - [Example 6: Character Deconstruction (by @cheerselflin)](#example-6-character-deconstruction-by-cheerselflin)
  - [Example 7: Behind the Scenes of Item Creation (by @ZHO\_ZHO\_ZHO)](#example-7-behind-the-scenes-of-item-creation-by-zho_zho_zho)
  - [Example 8: Children's Literacy Newsletter (by @lxfater)](#example-8-childrens-literacy-newsletter-by-lxfater)
  - [Example 9: Generate Material Texture (by @someidesign)](#example-9-generate-material-texture-by-someidesign)
  - [Example 10: Add Giant Creature to City Image (by @AI\_GIRL\_DESIGN)](#example-10-add-giant-creature-to-city-image-by-ai_girl_design)
  - [Example 11: Toy Disassembly Display (by @ZeroZ\_JQ)](#example-11-toy-disassembly-display-by-zeroz_jq)
  - [Example 12: Fluffy Plush Toy (by @toolfolio)](#example-12-fluffy-plush-toy-by-toolfolio)
  - [Example 13: Crystal Texture Emoji (by @ZHO\_ZHO\_ZHO)](#example-13-crystal-texture-emoji-by-zho_zho_zho)
  - [Example 14: Fluffy Inflatable Toy (by @gizakdag)](#example-14-fluffy-inflatable-toy-by-gizakdag)
  - [Example 15: Hand-drawn Isometric View (by @AmirMushich)](#example-15-hand-drawn-isometric-view-by-amirmushich)
  - [Example 16: Reveal Behind-the-Scenes of Photo Creation (by @icreatelife)](#example-16-reveal-behind-the-scenes-of-photo-creation-by-icreatelife)
  - [Example 17: Estimate Age from Face (by @Samann\_ai)](#example-17-estimate-age-from-face-by-samann_ai)
  - [Example 18: Historical Newspaper (by @TechieBySA)](#example-18-historical-newspaper-by-techiebysa)
  - [Example 19: Character Relationship Chart (by @KanaWorks\_AI)](#example-19-character-relationship-chart-by-kanaworks_ai)
  - [Example 20: Otome Game Setting Collection (by @KanaWorks\_AI)](#example-20-otome-game-setting-collection-by-kanaworks_ai)
  - [Example 21: Character Level Evolution (by @KanaWorks\_AI)](#example-21-character-level-evolution-by-kanaworks_ai)
  - [Example 22: Recursive Image (by @goodside)](#example-22-recursive-image-by-goodside)
  - [Example 23: Multi-Character Crossover Comic (by @canghecode)](#example-23-multi-character-crossover-comic-by-canghecode)
  - [Example 24: Coloring Figure Garage Kit (by @op7418)](#example-24-coloring-figure-garage-kit-by-op7418)
  - [Example 25: Golden Quote Card (by @stark\_nico99)](#example-25-golden-quote-card-by-stark_nico99)
  - [Example 26: Qingming Shanghe Tu Style Image (by @dotey)](#example-26-qingming-shanghe-tu-style-image-by-dotey)
  - [Example 27: Movie Storyboard Creation (by @jamesyeung18)](#example-27-movie-storyboard-creation-by-jamesyeung18)
  - [Example 28: Blackboard Chalk Drawing (by @TlanoAI)](#example-28-blackboard-chalk-drawing-by-tlanoai)
  - [Example 29: Miniature Self-Portrait (by @TechieBySA)](#example-29-miniature-self-portrait-by-techiebysa)
  - [Example 30: Generate Biography from Wikipedia (by @chrisfirst)](#example-30-generate-biography-from-wikipedia-by-chrisfirst)
  - [Example 31: Stylized Map (by @Mr\_AllenT)](#example-31-stylized-map-by-mr_allent)
- [🖼️ Nano Banana Examples](#️-nano-banana-examples)
  - [Case 1: Illustration to Figure(by @ZHO\_ZHO\_ZHO)](#case-1-illustration-to-figureby-zho_zho_zho)
  - [Case 2: Generate Ground View from Map Arrow(by @tokumin)](#case-2-generate-ground-view-from-map-arrowby-tokumin)
  - [Case 3: Real World AR Information(by @bilawalsidhu)](#case-3-real-world-ar-informationby-bilawalsidhu)
  - [Case 4: Extract 3D Buildings/Make Isometric Models(by @Zieeett)](#case-4-extract-3d-buildingsmake-isometric-modelsby-zieeett)
  - [Case 5: Photos of Yourself in Different Eras(by @AmirMushich)](#case-5-photos-of-yourself-in-different-erasby-amirmushich)
  - [Case 6: Multi-Reference Image Generation(by @MrDavids1)](#case-6-multi-reference-image-generationby-mrdavids1)
  - [Case 7: Automatic Photo Editing(by @op7418)](#case-7-automatic-photo-editingby-op7418)
  - [Case 8: Hand Drawing Controls Multi-Character Poses(by @op7418)](#case-8-hand-drawing-controls-multi-character-posesby-op7418)
  - [Case 9: Cross-View Image Generation(by @op7418)](#case-9-cross-view-image-generationby-op7418)
  - [Case 10: Custom Character Stickers(by @op7418)](#case-10-custom-character-stickersby-op7418)
  - [Case 11: Anime to Real Coser(by @ZHO\_ZHO\_ZHO)](#case-11-anime-to-real-coserby-zho_zho_zho)
  - [Case 12: Generate Character Design(by @ZHO\_ZHO\_ZHO)](#case-12-generate-character-designby-zho_zho_zho)
  - [Case 13: Color Line Art with Color Palette(by @ZHO\_ZHO\_ZHO)](#case-13-color-line-art-with-color-paletteby-zho_zho_zho)
  - [Case 14: Article Infographic(by @黄建同学)](#case-14-article-infographicby-黄建同学)
  - [Case 15: Change Multiple Hairstyles(by @balconychy)](#case-15-change-multiple-hairstylesby-balconychy)
  - [Case 16: Model Annotation Explanation Diagram(by @berryxia\_ai)](#case-16-model-annotation-explanation-diagramby-berryxia_ai)
  - [Case 17: Custom Marble Sculpture(by @umesh\_ai)](#case-17-custom-marble-sculptureby-umesh_ai)
  - [Case 18: Cook Based on Ingredients(by @Gdgtify)](#case-18-cook-based-on-ingredientsby-gdgtify)
  - [Case 19: Math Problem Reasoning(by @Gorden Sun)](#case-19-math-problem-reasoningby-gorden-sun)
  - [Case 20: Old Photo Colorization(by @GeminiApp)](#case-20-old-photo-colorizationby-geminiapp)
  - [Case 21: OOTD Outfit(by @302.AI)](#case-21-ootd-outfitby-302ai)
  - [Case 22: Character Clothing Change(by @skirano)](#case-22-character-clothing-changeby-skirano)
  - [Case 23: Multi-View Result Generation(by @Error\_HTTP\_404)](#case-23-multi-view-result-generationby-error_http_404)
  - [Case 24: Movie Storyboard(by @GeminiApp)](#case-24-movie-storyboardby-geminiapp)
  - [Case 25: Character Pose Modification(by @arrakis\_ai)](#case-25-character-pose-modificationby-arrakis_ai)
  - [Case 26: Generate image from line drawing(by @ZHO\_ZHO\_ZHO)](#case-26-generate-image-from-line-drawingby-zho_zho_zho)
  - [Case 27: Add Watermark to Image(by @AiMachete)](#case-27-add-watermark-to-imageby-aimachete)
  - [Case 28: Knowledge Reasoning Image Generation(by @icreatelife)](#case-28-knowledge-reasoning-image-generationby-icreatelife)
  - [Case 29: Red Pen Annotations(by @AiMachete)](#case-29-red-pen-annotationsby-aimachete)
  - [Case 30: Explosive Food(by @icreatelife)](#case-30-explosive-foodby-icreatelife)
  - [Case 31: Create Comic Book(by @icreatelife)](#case-31-create-comic-bookby-icreatelife)
  - [Case 32: Action Figure(by @icreatelife)](#case-32-action-figureby-icreatelife)
  - [Case 33: Map to Isometric Buildings(by @demishassabis)](#case-33-map-to-isometric-buildingsby-demishassabis)
  - [Case 34: Reference Image Controls Character Expression(by @ZHO\_ZHO\_ZHO)](#case-34-reference-image-controls-character-expressionby-zho_zho_zho)
  - [Case 35: Illustration Drawing Process Four-Panel(by @ZHO\_ZHO\_ZHO)](#case-35-illustration-drawing-process-four-panelby-zho_zho_zho)
  - [Case 36: Virtual Makeup Try-On(by @ZHO\_ZHO\_ZHO)](#case-36-virtual-makeup-try-onby-zho_zho_zho)
  - [Case 37: Makeup Analysis(by @ZHO\_ZHO\_ZHO)](#case-37-makeup-analysisby-zho_zho_zho)
  - [Case 38: Google Maps View of Middle-earth(by @TechHallo)](#case-38-google-maps-view-of-middle-earthby-techhallo)
  - [Case 39: Typographic Illustration Generation(by @Umesh)](#case-39-typographic-illustration-generationby-umesh)
  - [Case 40: Multiple Character Poses Generation(by @tapehead\_Lab)](#case-40-multiple-character-poses-generationby-tapehead_lab)
  - [Case 41: Product Packaging Generation(by @ZHO\_ZHO\_ZHO)](#case-41-product-packaging-generationby-zho_zho_zho)
  - [Case 42: Overlay Filter/Material(by @ZHO\_ZHO\_ZHO)](#case-42-overlay-filtermaterialby-zho_zho_zho)
  - [Case 43: Control Character Face Shape(by @ZHO\_ZHO\_ZHO)](#case-43-control-character-face-shapeby-zho_zho_zho)
  - [Case 44: Lighting Control(by @ZHO\_ZHO\_ZHO)](#case-44-lighting-controlby-zho_zho_zho)
  - [Case 45: LEGO Minifigure(by @ZHO\_ZHO\_ZHO)](#case-45-lego-minifigureby-zho_zho_zho)
  - [Case 46: Gundam Model Figure(by @ZHO\_ZHO\_ZHO)](#case-46-gundam-model-figureby-zho_zho_zho)
  - [Case 47: Hardware Exploded View(by @AIimagined)](#case-47-hardware-exploded-viewby-aiimagined)
  - [Case 48: Food Calorie Annotation(by @icreatelife)](#case-48-food-calorie-annotationby-icreatelife)
  - [Case 49: Extract Subject and Place on Transparent Layer(by @nglprz)](#case-49-extract-subject-and-place-on-transparent-layerby-nglprz)
  - [Case 50: Image Outpainting Repair(by @bwabbage)](#case-50-image-outpainting-repairby-bwabbage)
  - [Case 51: Ancient Map → Historical Scene Photo(by @levelsio)](#case-51-ancient-map--historical-scene-photoby-levelsio)
  - [Case 52: Fashion Moodboard Collage(by @tetumemo)](#case-52-fashion-moodboard-collageby-tetumemo)
  - [Case 53: Delicate Cute Product Photo(by @azed\_ai)](#case-53-delicate-cute-product-photoby-azed_ai)
  - [Case 54: Place Anime Statue in Real Life(by @riddi0908)](#case-54-place-anime-statue-in-real-lifeby-riddi0908)
  - [Case 55: Create an Itasha Car(by @riddi0908)](#case-55-create-an-itasha-carby-riddi0908)
  - [Case 56: Manga Composition(by @namaedousiyoka)](#case-56-manga-compositionby-namaedousiyoka)
  - [Case 57: Manga Style Conversion(by @nobisiro\_2023)](#case-57-manga-style-conversionby-nobisiro_2023)
  - [Case 58: Isometric Holographic Wireframe(by @tetumemo)](#case-58-isometric-holographic-wireframeby-tetumemo)
  - [Case 59: Minecraft-Style Scene Generation(by @tetumemo)](#case-59-minecraft-style-scene-generationby-tetumemo)
  - [Case 60: Apply Material Sphere to Logo(by @ZHO\_ZHO\_ZHO)](#case-60-apply-material-sphere-to-logoby-zho_zho_zho)
  - [Case 61: Floor Plan 3D Render(by @op7418)](#case-61-floor-plan-3d-renderby-op7418)
  - [Case 62: Reset Camera Parameters(by @hckinz)](#case-62-reset-camera-parametersby-hckinz)
  - [Case 63: Create an ID Photo(by @songguoxiansen)](#case-63-create-an-id-photoby-songguoxiansen)
  - [Case 64: Scene A6 Folding Card(by @Gdgtify)](#case-64-scene-a6-folding-cardby-gdgtify)
  - [Case 65: Design a Chess Set(by @Gdgtify)](#case-65-design-a-chess-setby-gdgtify)
  - [Case 66: Split-Contrast Style Photo(by @fofrAI)](#case-66-split-contrast-style-photoby-fofrai)
  - [Case 67: Jewelry Collection Design(by @Gdgtify)](#case-67-jewelry-collection-designby-gdgtify)
  - [Case 68: Merchandise Design(by @0xFramer)](#case-68-merchandise-designby-0xframer)
  - [Example 69: Model Holographic Projection (by @UNIBRACITY)](#example-69-model-holographic-projection-by-unibracity)
  - [Example 70: Giant Figure Scaffolding (by @songguoxiansen)](#example-70-giant-figure-scaffolding-by-songguoxiansen)
  - [Example 71: Building Extraction from Remote Sensing Image (by @lehua555)](#example-71-building-extraction-from-remote-sensing-image-by-lehua555)
  - [Example 72: Component Extraction (by @tetumemo)](#example-72-component-extraction-by-tetumemo)
  - [Example 73: Remove Burger Ingredients (by @bind\_lux, case provided by @jeanlucaslima)](#example-73-remove-burger-ingredients-by-bind_lux-case-provided-by-jeanlucaslima)
  - [Example 74: High-Resolution Image Restoration (by @op7418)](#example-74-high-resolution-image-restoration-by-op7418)
  - [Example 75: Generate Miniature Scene from Image (by @techhalla)](#example-75-generate-miniature-scene-from-image-by-techhalla)
  - [Example 76: Educational Comic (by @op7418)](#example-76-educational-comic-by-op7418)
  - [Example 77: Custom Character Emoji Pack Generation (by @vista8)](#example-77-custom-character-emoji-pack-generation-by-vista8)
  - [Example 78: Restore Partially Eaten Food (by @googlejapan)](#example-78-restore-partially-eaten-food-by-googlejapan)
  - [Example 79: Fighting Game Interface Creation (by @NanoBanana\_labs)](#example-79-fighting-game-interface-creation-by-nanobanana_labs)
  - [Example 80: Model Cross-Section (by @old\_pgmrs\_will)](#example-80-model-cross-section-by-old_pgmrs_will)
  - [Example 81: Pirate Wanted Poster (by @AI\_Kei75)](#example-81-pirate-wanted-poster-by-ai_kei75)
  - [Example 82: Merchandise Display Shelf (by @tokyo\_Valentine)](#example-82-merchandise-display-shelf-by-tokyo_valentine)
  - [Example 83: Comic Convention Booth (by @tokyo\_Valentine)](#example-83-comic-convention-booth-by-tokyo_valentine)
  - [Example 84: Line Art to Doodle Drawing (by @hAru\_mAki\_ch)](#example-84-line-art-to-doodle-drawing-by-haru_maki_ch)
  - [Example 85: Contemporary Art Exhibition Space (by @UNIBRACITY)](#example-85-contemporary-art-exhibition-space-by-unibracity)
  - [Example 86: Dark Gothic Tarot Card (by @ImperfectEngel)](#example-86-dark-gothic-tarot-card-by-imperfectengel)
  - [Example 87: Black and White Evolution Chart (by @ZHO\_ZHO\_ZHO)](#example-87-black-and-white-evolution-chart-by-zho_zho_zho)
  - [Example 88: Glass Bottle Souvenir (by @NanoBanana\_labs)](#example-88-glass-bottle-souvenir-by-nanobanana_labs)
  - [Example 89: Miniature Store (by @NanoBanana\_labs)](#example-89-miniature-store-by-nanobanana_labs)
  - [Example 90: Become a Vtuber (by @AI\_Kei75)](#example-90-become-a-vtuber-by-ai_kei75)
  - [Example 91: Train Station Movie Poster (by @AI\_Kei75)](#example-91-train-station-movie-poster-by-ai_kei75)
  - [Example 92: Movie Lounge (by @tokyo\_Valentine)](#example-92-movie-lounge-by-tokyo_valentine)
  - [Example 93: Slice Object with Cartoon Explosion Effect (by @Arminn\_Ai)](#example-93-slice-object-with-cartoon-explosion-effect-by-arminn_ai)
  - [Example 94: Character-Themed Train (by @tokyo\_Valentine)](#example-94-character-themed-train-by-tokyo_valentine)
  - [Example 95: Custom Theme Park (by @AI\_Kei75)](#example-95-custom-theme-park-by-ai_kei75)
  - [Example 96: Create Constellation Image (by @AI\_Kei75)](#example-96-create-constellation-image-by-ai_kei75)
  - [Example 97: Turn Image into Phone Wallpaper (by @ZHO\_ZHO\_ZHO)](#example-97-turn-image-into-phone-wallpaper-by-zho_zho_zho)
  - [Example 98: Make a Movie Poster (by @aiehon\_aya)](#example-98-make-a-movie-poster-by-aiehon_aya)
  - [Example 99: Turn X Account into Floppy Disk (by @icreatelife)](#example-99-turn-x-account-into-floppy-disk-by-icreatelife)
  - [Example 100: Make Reference Image Object Transparent (by @icreatelife)](#example-100-make-reference-image-object-transparent-by-icreatelife)
  - [Example 101: Fisheye Peephole Illustration (by @emakiscroll)](#example-101-fisheye-peephole-illustration-by-emakiscroll)
  - [Example 102: Superhero Interior Design (by @IqraSaifiii)](#example-102-superhero-interior-design-by-iqrasaifiii)
  - [Example 103: Custom Claw Machine (by @googlejapan)](#example-103-custom-claw-machine-by-googlejapan)
  - [Example 104: Typography Logo Design (by @aziz4ai)](#example-104-typography-logo-design-by-aziz4ai)
  - [Example 105: RPG Character Status UI (by @AI\_Kei75)](#example-105-rpg-character-status-ui-by-ai_kei75)
  - [Example 106: Convert Text Diagram to Pictograms (by @nobisiro\_2023)](#example-106-convert-text-diagram-to-pictograms-by-nobisiro_2023)
  - [Example 107: Drawing on a Pen Display (by @AI\_Kei75)](#example-107-drawing-on-a-pen-display-by-ai_kei75)
  - [Example 108: Create LINE Stamp Image (by @emakiscroll)](#example-108-create-line-stamp-image-by-emakiscroll)
  - [Example 109: Therapy for Childhood Self (by @samann\_ai)](#example-109-therapy-for-childhood-self-by-samann_ai)
  - [Example 110: Pixar-Style Portrait (by @NanoBanana\_labs)](#example-110-pixar-style-portrait-by-nanobanana_labs)
- [🙏 Acknowledge](#-acknowledge)

## 🍌 Nano Banana Pro Examples
<!-- Example 1: Ukiyoe Flash Card (by @MANISH1027512) -->
### Example 1: [Ukiyoe Flash Card](https://x.com/MANISH1027512/status/1992529793519120763) (by [@MANISH1027512](https://x.com/MANISH1027512))

|                              Output                              |
| :------------------------------------------------------------: |
| <img src="images/pro_case1/output.jpg" width="300" alt="Output Result"> |

**Prompt:**

```
Core Instruction: A Japanese Ukiyoe style collectible trading card design, vertical composition. The illustration style needs to closely mimic the visual aesthetics of "Demon Slayer", features include: ink outlines with varying thickness, traditional woodblock print color schemes, and dramatic dynamic composition.

Subject Description: The card protagonist is {Character Name} (Title: {Hashira Name/Title}), in a dynamic fighting pose, holding {Weapon Description}. The character is performing {Breathing Style Move Name}, surrounded by {Visual Effect Description} (e.g., giant flames / water dragon / whirlwind), these effects need to be presented in Traditional Japanese Sumi-e style.

Background and Material: The background needs to blend textured Holographic Foil effect, shimmering beneath the traditional ink elements.

Border: The image should have a decorative border composed of Traditional Japanese Patterns (such as Seigaiha or Asanoha). At the botto
